main = ".open-next/worker.js"
name = "rindechile"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "transparenta"
database_id = "c2d03ab2-b51b-4d73-839c-2f85ba2afecd"
migrations_dir = ".drizzle-out"

[observability]
enabled = false